apiVersion: v1
kind: Secret
metadata:
    name: renovate-env
type: Opaque
stringData:
    #ENC[AES256_GCM,data:/oxhhAE9HmmG4/qXIg05DNQ7D+0A7KpFTJBSVRwF6WdLLsKpsniY1eh1kQW2H7+MKSH/VhpbxNVJffChoHkyekTsM1/T+mPkU4N6KpZU+VPYdzYFAHVP7BcJkr9bX/Y=,iv:0DDA2+DDtHhSe6JdZleBKORapvvdbxJpjCGdl+M+dSc=,tag:uDzWAqLqrHO0OQYGYWSv5g==,type:comment]
    RENOVATE_AUTODISCOVER: ENC[AES256_GCM,data:ZdtDASA=,iv:ZKOpBbrC8mn/ynDrcYwisLyG/c7IAqAocqSnmxSMIJQ=,tag:UOviyil7e9vLUMz2Gsk1gQ==,type:str]
    #ENC[AES256_GCM,data:cKFAPUM1Cihc1t2NWKnBdhz9AMiqFGJ2gQcG4v+lolVizedUm/yzyJaOFmaFZGwHh1nVv1OU,iv:fzDNKoBO3KuwqF6tDTzPAWV8G6qsOQLPL8Q/OMDSHDI=,tag:wWl9k+Ya0Fy350+C8ZNhdg==,type:comment]
    RENOVATE_GIT_AUTHOR: ENC[AES256_GCM,data:3EHWhWkzmSuaEiNhW1B9VDvzfoJHhFVGIAHtenh0cbG43w==,iv:TBcgEvESQM8lrF3bIR0LM2pAQwnK3bhdtwIDkYfl+js=,tag:tJJzBx1pzB7yUR7cMauqUg==,type:str]
    RENOVATE_PLATFORM: ENC[AES256_GCM,data:vkYLHjFA,iv:AZUh28E+DlhUVunoS1sRxqmPepTe7WIcgSfDxxA8ZPA=,tag:b9sYaP5z6HyaycDhvaL1yQ==,type:str]
    RENOVATE_TOKEN: ENC[AES256_GCM,data:9p5H/wceTbpEwN7pQRaBPR/DLM+xcPf7N2U7SuWDGFRAkxxVU9xWhJY=,iv:ePtnmFdftiYkKrCPhdsjQk8MTaMwZTYyItCxtrK1zds=,tag:+f+Rp2tXRo7RrpiP0XsHAQ==,type:str]
    RENOVATE_GIT_PRIVATE_KEY: ENC[AES256_GCM,data:/Z2HRoT6Xpf8Zlp4hfEXmcfJFNnlbi33SFZPuRIS+J5CHLrZCp4lIWg19OnxafyWwexX0xbQOMHjI/MvSOaHCqt53IHK8EuXGPdidguwllvmeHDp7lI1AEUGXPFr/fTxXWe4JNTWhAweEWoPtYKSl93SQuCqT/AUz150TnocbrC52l3mIIl/OEjPd1kInpe6gY74FfdvlJKmmuLQhASBAYeox+vsJF0AmVm9yK8CjlX68N+bmFklkrsBFSF/RqOY1H9sxMzPWd7VUbT7qFEKPTbCNHVUzIMglXnyndGi2ovkh2GTJCXHZMECxqw5fyNSzizGT6KK388BgljwyrI8x6EFbZs/GTI2foOAUKzI6T4XOyZhS8xPnBfpm7z2A6Dh1Rt7/vJeN90SHb0ECiaCN9DHhwKvK4IMQpeL8PQll3IyuA2BykGjzldAeoCx7RJKYvFsA0PaKZhx3JhubW9mAhYfWju2CRzYWuR34DPkwgYtThLMbo/ZkXN/WmqCpKMgJi5fJUyDtzRLnizgsMJWr/BnEUpJRNIEisvsC0nQgDAG0eZYb9nMvDo0C0eqaw+59i5EUh1nCgQg/6EDr615ZY/fxSx+FK5CToxZp+4=,iv:C4yaqebhwfyiPdp5ucl7DU1/TjHsj+wdzYcLO6Hq71k=,tag:FYWcK0XjZQcyXespDmPb6g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-02-11T11:35:13Z"
    mac: ENC[AES256_GCM,data:sm+v5dCbeHyusCVVNRAmhGGgza3prcL83FFfKsOVmz3HkaMTG1zgRnsW5RYLe1NbI6v2QL9Js+u3uFdXdn+h/M+ysyw2cE1Xg5o7Q2xmK6yrZX3VuyWrLNGk4KA2sRCOK9wSXGfTzAb6HQl3iFrdpmor/oZC5a/vh7VDcqNEHfs=,iv:1NP+Q88i+uqWHMR8vNPp57PpS665UfFpexIDXCy7c/Y=,tag:V68L2O23ev6QapQdL1vojg==,type:str]
    pgp:
        - created_at: "2024-02-11T11:35:13Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            wV4DJK+IA+cNHtcSAQdA36bQ/DAyfwNSLA+XQ5GrfyKD66n6vlJCpXrucrTNBhQw
            wqsMoSonBbX3g0LURyCl9xF0uSgqsBbh/YGmaUB9iSqzP80G2/T7aa6IqfDlPb20
            0lEBUANlxKSB1jGRo+UMv8ecK56+m778dJHaRU/bImKFysnegw+53TPAh64cPJ2U
            t7OOIvLY9ivW/mvDVfwEu9iGO4bxN7br8Tlw/Ay2zzJzIC0=
            =oIi2
            -----END PGP MESSAGE-----
          fp: 7ED71373082E0FE0F90239710233D0893BBB9872
    encrypted_regex: ^(data|stringData|email|host|hosts)$
    version: 3.8.1
