apiVersion: apps/v1
kind: Deployment
metadata:
  name: pihole-deployment
  labels:
    app: pihole
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pihole
  template:
    metadata:
      labels:
        app: pihole
    spec:
      nodeSelector:
        disk: ssd
      containers:
      - name: pihole
        image: pihole/pihole:2023.10.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
          protocol: TCP
        - containerPort: 53
          protocol: UDP
        - containerPort: 53
          protocol: TCP
        envFrom:
          - secretRef:
              name: pihole-secret
        env:
          - name: TZ
            value: "Europe/Berlin"
          - name: PIHOLE_DNS_
            value: "192.168.1.1"
          - name: DNSMASQ_LISTENING
            value: "all"
      topologySpreadConstraints:
      # Prevent launching on the same host
      - maxSkew: 1
        topologyKey: "kubernetes.io/hostname"
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app: pihole

---
apiVersion: v1
kind: Service
metadata:
  name: pihole-service
  labels:
    app: pihole
spec:
  selector:
    app: pihole
  ports:
    - name: dns-usb
      protocol: UDP
      port: 53
      targetPort: 53
    - name: dns-tcp
      protocol: TCP
      port: 53
      targetPort: 53
    - name: panel
      protocol: TCP
      port: 80
  type: LoadBalancer
  loadBalancerIP: 192.168.10.2
  # This somehow breaks dns for pi ap clients
  #externalTrafficPolicy: Local
