apiVersion: apps/v1
kind: Deployment
metadata:
  name: esphome-deployment
  namespace: default
  labels:
    app: esphome
spec:
  replicas: 1
  selector:
    matchLabels:
      app: esphome
  template:
    metadata:
      labels:
        app: esphome
    spec:
      hostNetwork: true
      nodeSelector:
        disk: ssd
      containers:
      - name: esphome
        image: ghcr.io/esphome/esphome:2023.12.0
        volumeMounts:
        - name: esphome-config
          mountPath: /config
        - name: esphome-cache
          mountPath: /cache
      volumes:
      - name: esphome-config
        hostPath:
          path: /mnt/shared_data/k8s/esphome/config
      - name: esphome-cache
        emptyDir:
          sizeLimit: 1000Mi
