apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
    name: cluster-admin-secret
    labels:
        cnpg.io/reload: "true"
stringData:
    username: ENC[AES256_GCM,data:fTDBDEo=,iv:q5b3t+4WGjtBgO6CGbenr5gZl5o3djvT50lHwZAOLK4=,tag:HWkrDsXXx+ssmmwLghAqow==,type:str]
    password: ENC[AES256_GCM,data:Bd9am8rLjkBVBp7Xo7lHwG0x3No4kZa1pKsd1LdWhW0hkFYRet3r/g==,iv:bcox2A3DyVXtSfvYjVkCBlCRzewq130mImMWJIPnTBE=,tag:NEs92wShbJTgqfzG4wC2rA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-08-10T20:03:08Z"
    mac: ENC[AES256_GCM,data:UB7qltf65hEQwbgcznWzL83+4tbJ5Y0IFC1GUcZ+hO3EQgD2QbPtzPB5OWTux5/tCwguMiKn0crWCy02ANrT/XiwjoSeenY+/OocPdQc8GnHB4vjaHjfHInW2e7BLadqUxrGaUgcHutVBp75zfY7akbF+gyuB7qi4nrl5lav6nA=,iv:btmingmoYzIOqk7nZOYo6qtthy4kHzYS0WIVRKFc84c=,tag:Njtk3y277k3Tneqt4sJb9Q==,type:str]
    pgp:
        - created_at: "2024-08-10T20:03:08Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            wV4DJK+IA+cNHtcSAQdAdZ7bKaxpqUOmNYMppP7RZZE+wlG32ZcsDouxDPsi63Yw
            T0WSE4RUwtprWBGZMP8EMtrAXzKN0hwGfElc8XGcGAa7ZTdqPfL1id5fwFRnG78u
            0lEB6W+prhagv9g8UTSEUon+MylsB+gURYGp7Pl+C0/C5tRDkQAb53zPujasJic3
            oIlvxwLgVt1OI9zAf1/yxt7Vq2xACbCc8m3fr80qb/MjFXs=
            =VFW8
            -----END PGP MESSAGE-----
          fp: 7ED71373082E0FE0F90239710233D0893BBB9872
    encrypted_regex: ^(data|stringData|email|host|hosts)$
    version: 3.9.0
