apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
    name: cluster-admin-secret
    namespace: postgres
    labels:
        cnpg.io/reload: "true"
stringData:
    username: ENC[AES256_GCM,data:2OlvrRg=,iv:mZQeKDXXREzDPN3YbSsDG7/uhD88/uZ1X+KMI2i893c=,tag:F0AQaSGtyXADbU5Wyh/d3g==,type:str]
    password: ENC[AES256_GCM,data:2hGrzoEz8K5SiUvxJ1J0nMC5Oc4JqgeRQFm+P/OgvcoPX/Kx/n8sug==,iv:llYdBvZ9nzPNfoqKk23Sh80jKLJQAX4WNywwP+IJQo0=,tag:GKPdP+02A3ENDtmDxUNUNw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-08-10T21:19:44Z"
    mac: ENC[AES256_GCM,data:P02QBBQQLGbXetbWI319hQh1Uz/ZxJQSDpfnabwzZQe/+vg3h5oCdNgbwFNRSG3+ODV7uvt6cxYZFzdg5iFIzB7+17ZcBz1xpvLyOiYqsZqcrx0l+20Iadg7fdDOnIlexfpKVWtvSOwUg/pdZH23BFgeOvEa2di1Z6wxR0K3ZfE=,iv:kj5Qfp5NQbvaQKejpJikHcq0WpLotw7b4O/TdIgZ3wA=,tag:aR95o/0NS4v0XX6eXcLG/w==,type:str]
    pgp:
        - created_at: "2024-08-10T21:19:44Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            wV4DJK+IA+cNHtcSAQdABhqiz4jLJSpfFYHv8zDFVYwsufXIIRu6DTD8+Z+2TA0w
            XXR6gl3lmCnqOhZI7lq5F4CE1vAfEKu5eeb0qqy1KqN79p3YzaTSVvlT2IQhbLwH
            0lEBis6TY0t6Aa0c4DcDTGChMAWK172SCPFDyMrTqi8lZWtUUP91qqr0UCcIa8Nu
            gXMDp6C874oJhHXUwEMTLOO9CejKi59wxH9nzAxqCr8S/jw=
            =0oyc
            -----END PGP MESSAGE-----
          fp: 7ED71373082E0FE0F90239710233D0893BBB9872
    encrypted_regex: ^(data|stringData|email|host|hosts)$
    version: 3.9.0
