---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: flannel
  namespace: kube-flannel
spec:
  chart:
    spec:
      chart: flannel
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: flannel
  interval: 1m0s
  values:
    flannel:
      backend: "vxlan"
