---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: flannel
  namespace: kube-flannel
spec:
  valuesFrom:
    - kind: Secret
      name: flannel-secret
      valuesKey: psk
      targetPath: flannel.psk
  chart:
    spec:
      chart: flannel
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: flannel
  interval: 1m0s
  values:
    flannel:
      backend: "vxlan"
      backendPort: 51830
      backendPortIPv6: 51831
