apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: synapse-ingress
    namespace: default
    annotations:
        cert-manager.io/cluster-issuer: private-issuer
spec:
    ingressClassName: nginx-external
    rules:
        - host: ENC[AES256_GCM,data:QbGOSrxLeAs+/jIUVr6mFa62SfK8,iv:bY+/AJ21Twa7PAziwg5Zl0TTyzWAN8XTyAWG1K0TiZ4=,tag:G1ZS2zlDBl71moEXwu6IkA==,type:str]
          http:
            paths:
                - pathType: Prefix
                  path: /
                  backend:
                    service:
                        name: synapse-service
                        port:
                            number: 80
                - pathType: Prefix
                  path: /.well-known/matrix
                  backend:
                    service:
                        name: delegation-service
                        port:
                            number: 80
    tls:
        - hosts:
            - ENC[AES256_GCM,data:3vbXrfLELm4dxsI5AwEeYv6NlaoL,iv:w1hzo97GMFR82wxMNvg6qzwbhWwcB7RcQWYmVRb73Pw=,tag:bzznI5cN2joAFfzXW2avGw==,type:str]
          secretName: synapse-tls
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-11-20T09:27:51Z"
    mac: ENC[AES256_GCM,data:pyO/vL5lu8mm/hqK1X3rb5cA8LW4cg8P4iQz5xFhFcM2907nWuHJyXlRMm3Je3vppDSVA8oA54l96q76JUDPPogI+OPwZcMioU1ytzJ3uI5qp8alIJ0tUGz9QTiQElh8X8rDy+TVBzbAeLudgchjEh6VaV82weeU8WMA8DdalaQ=,iv:S4f1pmRdwn36IXNymSEjw+4G5OcfbwXz7vjNLgV5hjs=,tag:+GHyst9weum2KKvmE6qCGw==,type:str]
    pgp:
        - created_at: "2023-11-20T09:27:51Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            wV4DJK+IA+cNHtcSAQdAqULBxFbf1yJmfVZN+z69qV2I3yvUh67rEvpY4AGY1Q8w
            f7br999mLd2KPNGWu9dYC5/SWb2ucOeYGbN4PFhLD5aoLt7r0IZ2JskDsqDKyt84
            0lEB4wn/vnoHAtqKY4gnh03MMbRhfvci+VC1jDA6w4XtGJS0oi7YB1oM4RvvV9pi
            pVp4w0FP+J8THy0KWnNam4B/H32FIHEXV7OosSO9Hfp/5oA=
            =4BJo
            -----END PGP MESSAGE-----
          fp: 7ED71373082E0FE0F90239710233D0893BBB9872
    encrypted_regex: ^(data|stringData|email|host|hosts)$
    version: 3.8.1
