---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  chart:
    spec:
      chart: ingress-nginx
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
      version: 4.11.2
  interval: 1m0s
  values:
    controller:
      allowSnippetAnnotations: true
      service:
        loadBalancerIP: 192.168.10.30
      config:
        proxy-body-size: "50m"
        compute-full-forwarded-for: "true"
        use-forwarded-headers: "true"
      ingressClassResource:
        name: nginx
        controllerValue: "k8s.io/ingress-nginx"

