apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudnative-pg
  namespace: argocd
spec:
  project: default
  source:
    chart: cloudnative-pg
    repoURL: https://cloudnative-pg.github.io/charts
    targetRevision: 0.23.0
    helm:
      releaseName: cloudnative-pg
      valuesObject:
        monitoring:
          podMonitorEnabled: true

  destination:
    server: "https://kubernetes.default.svc"
    namespace: postgres
