apiVersion: v1
kind: Secret
metadata:
    name: emqx-secret
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:etg54vo=,iv:XaAySbBmBx+hDZSB1Kr6LNnBe+kWPgzVY5XbTTO/Csg=,tag:0zGI0EMo/KSjVJUN4J8mFA==,type:str]
    password: ENC[AES256_GCM,data:tOdbvOqwqcdyiIUCf3UJDTEb99gA1NpR,iv:IT/1ESIVRNxmB29FiY25Yp4c+zGYtFCK5KnNNQjo2Bk=,tag:AfiG71Uh3cUezlsWkrleaw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-11-10T20:13:05Z"
    mac: ENC[AES256_GCM,data:pvlqGvwC8IDH7lzftUfRiTMADAmgezJVEcyRDnrlMygUl3hgdcpu0KyBmCurHxDzCW/VkOng1Ztg0SR4w3lCKzX5oo+Beky0n6GNnItN02h1taRBaa3tXUooYv8F5zyOUt/39CyznAJzJ45sqI14HiBHwnN32vvMalIsPfzgkEI=,iv:FUv8i0TVP7Nbiw+y8H2D9jHFbizvSjkAXsDPHMiiAvg=,tag:Q38TuasijG0myFcUENMWew==,type:str]
    pgp:
        - created_at: "2023-11-10T20:13:05Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            wV4DJK+IA+cNHtcSAQdAcT8eRhGPrXzGvwZc/hIgxx4ndf8JmQ+z2CR/83uhmFAw
            5JnRBVyvvH+GyNNVH201Xy346ZYrufYe44mBiiM+PpI4Hd6n1r6oqu4b4k016tOU
            0lEBtzmTb9fJGJ01yD0Y87mVCTkjKyG/uii9ZOn3PZRQe4or0Rke6/duBET3kuRk
            n1z7Zgqy7NsUVCehj8XJ6Qbxy/SlAvkh40N8wady0YqwLXQ=
            =fJvR
            -----END PGP MESSAGE-----
          fp: 7ED71373082E0FE0F90239710233D0893BBB9872
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
