---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: emqx
  namespace: default
spec:
  chart:
    spec:
      chart: emqx
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: emqx
      version: 5.3.0
  interval: 1m0s
  values:
    emqxConfig:
    - name: EMQX_DASHBOARD__DEFAULT_USERNAME
      valueFrom:
        secretKeyRef:
          name: emqx-secret
          key: dashboard_username
    - name: EMQX_DASHBOARD__DEFAULT_PASSWORD
      valueFrom:
        secretKeyRef:
          name: emqx-secret
          key: dashboard_password
    - name: EMQX_AUTHENTICATION__1__DATABASE
      valueFrom:
        secretKeyRed:
          name: emqx-secret
          key: database
    - name: EMQX_AUTHENTICATION__1__USERNAME
      valueFrom:
        secretKeyRed:
          name: emqx-secret
          key: database_user
    - name: EMQX_AUTHENTICATION__1__PASSWORD
      valueFrom:
        secretKeyRed:
          name: emqx-secret
          key: database_password
    EMQX_AUTHENTICATION__1__BACKEND: postgresql
    EMQX_AUTHENTICATION__1__MECHANISM: password_based
    EMQX_AUTHENTICATION__1__PASSWORD_HASH_ALGORITHM__NAME: bcrypt
    EMQX_AUTHENTICATION__1__QUERY: "SELECT password_hash FROM mqtt_user where username = ${username} LIMIT 1"
    EMQX_AUTHENTICATION__1__SERVER: "postgresql-service:5432"

    ingress:
      dashboard:
        enabled: true
        ingressClassName: nginx
        hosts:
          - emqx.kokev.de
        tls:
          - hosts:
            - emqx.kokev.de
            secretName: kokev-wildcard-tls


