---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: emqx
  namespace: default
spec:
  valuesFrom:
    - kind: Secret
      name: emqx-secret
      valuesKey: dashboard_username
      targetPath: emqxConfig.EMQX_DASHBOARD__DEFAULT_USERNAME
    - kind: Secret
      name: emqx-secret
      valuesKey: dashboard_password
      targetPath: emqxConfig.EMQX_DASHBOARD__DEFAULT_PASSWORD
    - kind: Secret
      name: emqx-secret
      valuesKey: database
      targetPath: emqxConfig.EMQX_EMQX_AUTHENTICATION__1__DATABASE
    - kind: Secret
      name: emqx-secret
      valuesKey: database_username
      targetPath: emqxConfig.EMQX_EMQX_AUTHENTICATION__1__USERNAME
    - kind: Secret
      name: emqx-secret
      valuesKey: database_password
      targetPath: emqxConfig.EMQX_EMQX_AUTHENTICATION__1__PASSWORD
  chart:
    spec:
      chart: emqx
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: emqx
      version: 5.7.0
  interval: 1m0s
  values:
    service:
      type: LoadBalancer
      loadBalancerIP: 192.168.10.5
      annotations:
        external-dns.alpha.kubernetes.io/hostname: mqtt.kokev.de
    ssl:
      enabled: true
      useExisting: false
      dnsnames:
        - mqtt.kokev.de
      issuer:
        name: kokev-issuer

    extraVolumes:
      - name: emqx-config
        configMap:
          name: emqx-config
    extraVolumeMounts:
      - name: emqx-config
        mountPath: /opt/emqx/etc/acl.conf
        subPath: "acl.conf"
    emqxConfig:
      EMQX_AUTHENTICATION__1__BACKEND: postgresql
      EMQX_AUTHENTICATION__1__MECHANISM: password_based
      EMQX_AUTHENTICATION__1__PASSWORD_HASH_ALGORITHM__NAME: bcrypt
      EMQX_AUTHENTICATION__1__QUERY: "SELECT password_hash FROM mqtt_user where username = ${username} LIMIT 1"
      EMQX_AUTHENTICATION__1__SERVER: "postgresql-service:5432"
      EMQX_LISTENERS__SSL__DEFAULT__SSL_OPTIONS__CERTFILE: /tmp/ssl/tls.crt
      EMQX_LISTENERS__SSL__DEFAULT__SSL_OPTIONS__KEYFILE: /tmp/ssl/tls.key


    metrics:
      enabled: true
    ingress:
      dashboard:
        enabled: true
        ingressClassName: nginx
        annotations:
          cert-manager.io/cluster-issuer: "kokev-issuer"
        hosts:
          - emqx.kokev.de
        tls:
          - hosts:
            - emqx.kokev.de
            secretName: emqx-dashboard-tls
    resources:
      #limits:
      #  cpu: 500m
      #  memory: 512Mi
      requests:
        cpu: 500m
        memory: 512Mi
        #topologySpreadConstraints:
        #  maxSkew: 1
        #  topologyKey: "kubernetes.io/hostname"
        #  whenUnsatisfiable: ScheduleAnyway


