---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: emqx
  namespace: default
spec:
  chart:
    spec:
      chart: emqx
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: emqx
      version: 5.3.0
  interval: 1m0s
  values:
    emqxConfig:
    - name: EMQX_DASHBOARD__DEFAULT_USERNAME
      valueFrom:
        secretKeyRef:
          name: emqx-secret
          key: username
    - name: EMQX_DASHBOARD__DEFAULT_PASSWORD
      valueFrom:
        secretKeyRef:
          name: emqx-secret
          key: password
    ingress:
      dashboard:
        enabled: true
        ingressClassName: nginx
        hosts:
          - emqx.kokev.de
        tls:
          - hosts:
            - emqx.kokev.de
            secretName: kokev-wildcard-tls


