SERVER_USER: ENC[AES256_GCM,data:lYBnVm7Q0mQCFQ==,iv:8sQlgDoNSRcEJe/8GqGfy0zcIerJSq5RLL5Xi7QODdY=,tag:RVLuGkh6QO7KJpP1yLkJAg==,type:str]
SERVER_PASSWORD: ENC[AES256_GCM,data:4eji5fjJ9bzfLeD3I3to+tnZA90vGRLkoOOnxYzo/wA=,iv:NJTQ/DYudy2ImgAyvqVW+a3d4ltE9SNH/AtWCHjB7zY=,tag:M87t5D53vB37BX7VaE4wIQ==,type:str]
server_config: ENC[AES256_GCM,data:RAEuUpByilg/LxpHfAomEpHfhOJMuZm/aRs7JH7TIvpVHYxs9vhh3z83wK2AniulQ/HUVKN2veYXaG9i4bfDFvS9QjkowvzujjhPnKiE4DBVzLzYT1OLAPhPxRkDoxRjwyj266OaLrnjj7CIvQ9iQyYqPNcC37X+1wr5FDpFssdJlo4X6fsrqmLzj4k7BqRvcO75Ni6bFqUH0mow90sdTzGK6brfP2gjz8a0dk9n3szwLdHMBtuN711AQpRjWynq1yG/COJ7dkva+3o4hrRJYjetd94k7LhxErmmLkTvKBewaA9ybOaKGpRz2eTuSyyFPlTvS/tsxgFl+sFJQeX6xZ6dAIYvqbop2M5DgaNsMd4+br3WopApK+1B4lG1VIvAgih4oB0ggIYfUf8XoD3oVpHQSGOuDypEsg==,iv:GCsr1CRCUm/jSHfI9eWpE7f5lEVj6cUSnJ3IYxYMD3Y=,tag:BIrZBsy8m5QN0/FLgTSbTA==,type:str]
smtp_user: ENC[AES256_GCM,data:9TAXLl/o2TqJ1Gi43Cw=,iv:K0NvnVEDlzxDuwFapbhUU80Cb/lpJ59HDgj+wRh4hLs=,tag:k4q7+qoU58Xuh2URsDU2dQ==,type:str]
smtp_password: ENC[AES256_GCM,data:hiA+9KLhtf7TSrZ1p5hPkkaqo/DJEM6K,iv:APeOLiK0L6sfaAyZRrE8Qjvko2YNcbNlbYIirY6ujTQ=,tag:5tXYMEPQW+tSBWyVutQo4A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-02-12T19:06:05Z"
    mac: ENC[AES256_GCM,data:34bmZ0d62CtNYmML7DVUA19wuYIhM2tVKtQ5TigA50d9dLNyN+6jjqtot8g8v8fHAd6LXiIM2CEL/Mkjx1JMn5aGfq7Ivnj+wCRQLzmLVZaes3mlaPf+x+vNnPoNcmJWEd+6fn9cXMzBgXFuaYG+qt0rmGcq/qKY+YabMqHLew0=,iv:ydAniYAjrHfRJBMHH7Dq5hiv5JlXcN+n93bJug/Vs18=,tag:gsZov4V+YFH1LVlRC5uwgw==,type:str]
    pgp:
        - created_at: "2025-02-12T19:06:05Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            wV4DJK+IA+cNHtcSAQdA5Fke63HZHkv62hwWC9iX5I/4jDKsgUFp16K7dcWWJ2cw
            3S6gB4EDBYOq3dY9ZET7Kx5Xwa18+QtEXTB4lBCTynqVHI2DsWlc+iEMRDS8nWpx
            0lEBSfDFjv/4AzLNY0FbG47+KQOgAXoxirOnDzmt91GN9RkHcYtB55ThVtsG6kl1
            GKIjtD8h6dW7XIO1CBVkhvXdwCl2EcHIfgTPfC3zz62ae3U=
            =jTuE
            -----END PGP MESSAGE-----
          fp: 7ED71373082E0FE0F90239710233D0893BBB9872
    encrypted_regex: ^(.*)$
    version: 3.9.1
