wg0.conf: ENC[AES256_GCM,data:r5lc9BfaV4fN7rnxyW+oB1mGZdWxxyxghorL3IrdEDlu+SWZo6ubFWBZlZbWPPqrRb7v5oOPwZGANtXmkur3NJMsWxpIUEuOuokk8ckBcvnEk+4+pHCVpu3qMYbo8r1RjMbIoMSNQor0UKHR8OWQETcuJSjKAvb6SpiNNchTwr2betbRJilU+775UAqNkBgIMLJvuza6Gd6I01WxnH7+1P92K/EPcZ45yeuAuOKNMWLZrtjvLu5rFYHHDE3gWnnJhm+GXGt8Pbsq9Uh39H+uamq5ckEN39pc8iVLht/YR0+dNbUuq4qAklzwscXz/cem4PtbLOjavtUoInbqoosOH+MkiTIUPuObRzYpZwwCGE5LXcrEsHpRRfMz5NIGcwqpE4gc2wU8ETcnkL4wwuo2CY6kF+A1iGi0eAa0nAHuuQTF5fheBR3mlj26bOR4ivNkuOIf4zBOMvuv/YVopg4mUu0Gv/jMEeOv61d3XVtGBdF+D06p0iDa4uclkjtPcmKTus3MWKLEBbkmCMZ0weOq9Dv2MMdpSsLkuKdrvm0Ayd1S+UvtPG0tuRxgI+rNFHuzpPt+ibD/WHRd+S0Al4k8sK6pIGQF5TdrDuT7t79/R8i0yYLqG8rzj7irmQsCqQ0jc1mmuLR2jVxYJJ3rAuyG7qoh4/b6WLRQuSw6W+V73qV2z6X41ei3iFKchYfuiklYtDxHD3CGMVX9Q9ciD3z1EwEEDjylJUs3B18mL/SGQnKIbPp3qTspyOhS74PwpGuTCFNitFCLvnk4BAuK/MwheN0zylArrlgyb6xVztRDJOFd2nkjhB8AxIYnpPRhnDjuKhQJ+YESOR7NC0aCu1kviQ5w4o9+X21AjK/AYTygs2Epxh6cOZ7peXtdWfVU79GYQ82lUvINEcY44WVy3Nmj55X6KTYlqiDUi99BEcxpUVmrpcGsmnLM6IL1Qb30BdqcC7uJfqx/uOhQ,iv:0bHyja+w5L+3hgtgfR/3kvMOPFqW5gO7/PeX1BskuZA=,tag:sXB350H4cNFaxYHzXtfzIQ==,type:str]
sops:
    lastmodified: "2026-03-30T14:47:02Z"
    mac: ENC[AES256_GCM,data:9luIYXxkvontTfzxoDHE8ohlEJqHXX89WTpPXRE0FIUa9IzwhnZzbKtSPK4rIf+ULBeMTD+qxDtcVDwEWLfsubC1aAFay2ulaYV8tPYNuSSGc71YNliDBQ63iqAqwotTcOswoftQmql+si/hBT97GHCUTCwlZd3D7RabJs5vXXA=,iv:1yZIHlBsrfxCqFbtyvqNIVwNI4SRLHYvBGSyP40gAms=,tag:mAFSb3OUNXIqGv2uVntXIw==,type:str]
    pgp:
        - created_at: "2025-02-09T22:14:15Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            wV4DJK+IA+cNHtcSAQdAxcfcOHfYwIsyqkSQALjkpSCM8vFTUI38SzEpYYTYXRAw
            IMUsXg7FPfPzmbKbWsZ5ShMVGOh9YNPFrxpXzz8emrGiQVwHs73jVI3tfYDwFijb
            0lEBKM8LzH0LQ0F9cLsV3NuzBsOSw4ZA+4jWw/JOMVCcD2T2ichk7JrJM8idtIjk
            4lTqCa4Pdf16gk23DJQr6t5t8RlObz4l9YwjKkpOfvWMKpA=
            =sDql
            -----END PGP MESSAGE-----
          fp: 7ED71373082E0FE0F90239710233D0893BBB9872
    encrypted_regex: ^(.*)$
    version: 3.10.2
