apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgresql-deployment
  namespace: default
  labels:
    app: postgresql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
      - name: postgresql
        image: postgres:15.10-alpine@sha256:fd3abc9557df27613bd5c5e6608fc62fb04dc90c8e79c3322348d600e4b75478
        ports:
        - containerPort: 5432
          protocol: TCP
        env:
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: password
          - name: LANG
            value: de_DE.utf8
          - name: POSTGRES_INITDB_ARGS
            value: --locale-provider=icu --icu-locale=de-DE
        volumeMounts:
        - name: psql-config
          mountPath: /var/lib/postgresql/data
        resources:
          requests:
            memory: "512Mi"
      volumes:
      - name: psql-config
        hostPath:
          path: /root/docker/postgres/data
      # TODO: integrate into glusterfs
      nodeSelector:
        kubernetes.io/hostname: raspberrypi-server
---
apiVersion: v1
kind: Service
metadata:
  name: postgresql-service
  namespace: default
  labels:
    app: postgresql
spec:
  selector:
    app: postgresql
  ports:
    - name: psql
      protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP

