apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-unsigned
  namespace: default
spec:
  selector:
    matchLabels:
      app: nginx-unsigned
  replicas: 3 
  template:
    metadata:
      labels:
        app: nginx-unsigned
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
