{
 "title": "Solar",
 "time": { "from": "now/d", "to": "now" },
 "refresh": "31s",
 "panels": [
  { "title": "Gesamt", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Solarmodul Gesamtlaufzeit",
   "type": "stat",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expression": "($total_solar - $daily_last) / ($day_count -1)",
     "type": "math"
    },
    { "expression": "solar_data_daily", "reducer": "count", "type": "reduce" },
    {
     "conditions": [
      {
       "evaluator": {
        "params": [
         0,
         0
        ],
        "type": "gt"
       },
       "operator": { "type": "and" },
       "query": {
        "params": []
       },
       "reducer": {
        "params": [],
        "type": "avg"
       },
       "type": "query"
      }
     ],
     "downsampler": "mean",
     "expression": "solar_data_daily",
     "reducer": "sum",
     "type": "reduce",
     "upsampler": "fillna"
    },
    {
     "expression": "$kosten/($strompreis / 1000) - $total_solar",
     "type": "math"
    },
    { "expression": "$wh_needed / $day_avg", "type": "math" },
    {
     "expression": "-$kosten + ($strompreis * $total_solar / 1000)",
     "type": "math"
    },
    {
     "expression": "$kosten / ($total_solar / 1000)",
     "type": "math"
    },
    { "expression": "($kosten + $profit) / $kosten", "type": "math" }
   ]
  },
  {
   "title": "Bester Tag",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "mqtt_sensors",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "topic::tag", "operator": "=", "value": "solar/dtu/bkw/daily_yield" }
     ]
    },
    { "expression": "($A / 1000) * 0.3237", "reducer": "max", "settings": { "mode": "dropNN" }, "type": "math" }
   ]
  },
  {
   "title": "Aktuelle Platzierung",
   "type": "stat",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$count + 1", "type": "math" },
    { "expression": "$next - $current_wh_scalar", "type": "math" },
    {
     "expression": "($wh_needed / $current_power) * 60 * 60",
     "type": "math"
    },
    {
     "expression": "(($number1_wh - $current_wh_scalar) / $current_power) * 60 * 60",
     "type": "math"
    }
   ]
  },
  {
   "title": "Profit Heute",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "($wh / 1000) * 0.3237", "type": "math" }
   ]
  },
  {
   "title": "Profit Gestern",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "($wh / 1000) * 0.3237", "type": "math" }
   ]
  },
  {
   "title": "Profit Woche",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "($wh / 1000) * 0.3237", "type": "math" }
   ]
  },
  {
   "title": "Profit Monat",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "($wh / 1000) * 0.3237", "type": "math" }
   ]
  },
  {
   "title": "Profit Jahr",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "($wh / 1000) * 0.3237", "type": "math" }
   ]
  },
  {
   "title": "Profit Gesamt",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "($wh / 1000) * 0.3237", "type": "math" }
   ]
  },
  { "title": "Eingestellter Zeitraum", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Täglicher Ertrag",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    { "expression": "$wh1 + $wh2", "type": "math" },
    { "expression": "$wh * (0.3237 / 1000)", "type": "math" }
   ]
  },
  {
   "title": "Wöchentlicher ertrag",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "downsampler": "sum",
     "expression": "wh",
     "type": "resample",
     "upsampler": "fillna",
     "window": "1w"
    },
    { "expression": "$wh_week * (0.3237 / 1000)", "type": "math" }
   ]
  },
  {
   "title": "Monatlicher ertrag",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "downsampler": "sum",
     "expression": "$wh1 + $wh2",
     "type": "math",
     "upsampler": "fillna",
     "window": "1M"
    },
    { "expression": "$wh * (0.3237 / 1000)", "type": "math" }
   ]
  },
  {
   "title": "Stromerzeugung",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mqtt_sensors",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "topic::tag", "operator": "=", "value": "solar/dtu/bkw/port/1/power" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mqtt_sensors",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "topic::tag", "operator": "=", "value": "solar/dtu/bkw/port/2/power" }
     ]
    },
    { "expression": "$w1 + $w2", "reducer": "mean", "type": "math" }
   ]
  },
  {
   "title": "Stromerzeugung",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1h" ], "type": "time" }
     ],
     "measurement": "mqtt_sensors",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ],
     "tags": [
      { "key": "topic::tag", "operator": "=", "value": "solar/dtu/bkw/port/1/energy" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "1h" ], "type": "time" }
     ],
     "measurement": "mqtt_sensors",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ],
     "tags": [
      { "key": "topic::tag", "operator": "=", "value": "solar/dtu/bkw/port/2/energy" }
     ]
    },
    { "expression": "$wh1 + $wh2", "type": "math" },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "solar_forecast",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Leistung",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "mqtt_sensors",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "topic::tag", "operator": "=", "value": "solar/dtu/bkw/current_power" }
     ]
    }
   ]
  },
  {
   "title": "Leistung",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "mqtt_sensors",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "topic::tag", "operator": "=", "value": "solar/dtu/bkw/port/1/power" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "mqtt_sensors",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "topic::tag", "operator": "=", "value": "solar/dtu/bkw/port/2/power" }
     ]
    }
   ]
  },
  {
   "title": "Spannung",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "mqtt_sensors",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "topic::tag", "operator": "=", "value": "solar/dtu/bkw/port/1/voltage" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "mqtt_sensors",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "topic::tag", "operator": "=", "value": "solar/dtu/bkw/port/2/voltage" }
     ]
    }
   ]
  },
  {
   "title": "Strom",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "mqtt_sensors",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "topic::tag", "operator": "=", "value": "solar/dtu/bkw/port/1/curr" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "mqtt_sensors",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "topic::tag", "operator": "=", "value": "solar/dtu/bkw/port/2/curr" }
     ]
    }
   ]
  },
  {
   "title": "Energie",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "wh_module", "reducer": "sum", "type": "reduce" },
    { "expression": "($wh / 1000) * 0.3237", "type": "math" }
   ]
  },
  {
   "title": "Maximale Leistung",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "A", "reducer": "max", "settings": { "mode": "dropNN" }, "type": "reduce" }
   ]
  },
  {
   "title": "Netzfrequenz",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "mqtt_sensors",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      {
       "key": "topic::tag",
       "operator": "=",
       "value": "solar/dtu/bkw/inverter/22069994735669/grid_freq"
      }
     ]
    }
   ]
  },
  {
   "title": "Temperatur",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "mqtt_sensors",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      {
       "key": "topic::tag",
       "operator": "=",
       "value": "solar/dtu/bkw/inverter/22069994735669/temperature"
      }
     ]
    }
   ]
  },
  {
   "title": "Effizienz",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expression": "$total_power / ($power1 + $power2)",
     "type": "math"
    }
   ]
  },
  {
   "title": "Netzspannung",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "mqtt_sensors",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      {
       "key": "topic::tag",
       "operator": "=",
       "value": "solar/dtu/bkw/inverter/22069994735669/grid_voltage"
      }
     ]
    }
   ]
  },
  { "title": "Vorhersage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 } },
  {
   "title": "Heute",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "A", "reducer": "sum", "settings": { "mode": "dropNN" }, "type": "reduce" },
    { "expression": "($B / 1000) * 0.3237", "type": "math" }
   ]
  },
  {
   "title": "Morgen",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "A", "reducer": "sum", "settings": { "mode": "dropNN" }, "type": "reduce" },
    { "expression": "($B / 1000) * 0.3237", "type": "math" }
   ]
  }
 ]
}