---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: ping-exporter
  namespace: monitoring
spec:
  interval: 24h
  url: https://raw.githubusercontent.com/czerwonk/ping_exporter/main/dist/charts/
