---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: ping-exporter
  namespace: monitoring
spec:
  chart:
    spec:
      chart: ping-exporter
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: ping-exporter
      version: 1.1.0
  interval: 1m0s
  values:
    image:
      tag: "v1.1.0"
    config:
      targets:
        - 202.61.194.167
        - 192.168.1.1
      dns:
        nameserver: 192.168.10.2
