---
apiVersion: v1
kind: Service
metadata:
  name: esphome-service
  namespace: default
  labels:
    app: esphome
spec:
  selector:
    app: esphome
  ports:
    - name: panel
      protocol: TCP
      port: 80
      targetPort: 6052
  type: ClusterIP
