apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegraf-deployment
  namespace: monitoring
  labels:
    app: telegraf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telegraf
  template:
    metadata:
      labels:
        app: telegraf
    spec:
      containers:
      - name: telegraf
        image: telegraf:1.30.1-alpine
        volumeMounts:
        - name: telegraf-config
          mountPath: /etc/telegraf
        resources:
          requests:
            memory: "64Mi"
      volumes:
      - name: telegraf-config
        hostPath:
          path: /mnt/shared_data/k8s/telegraf/config
