---
apiVersion: v1
kind: Service
metadata:
  name: zigbee2mqtt
  namespace: default
  labels:
    app: zigbee2mqtt
spec:
  selector:
    app: zigbee2mqtt
  ports:
    - name: frontend
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP

