apiVersion: v1
kind: Service
metadata:
  name: node-red-service
  namespace: default
  labels:
    app: node-red
spec:
  selector:
    app: node-red
  ports:
    - name: panel
      protocol: TCP
      port: 80
      targetPort: 1880
  type: ClusterIP

