---
apiVersion: v1
kind: Service
metadata:
  name: chhoto
  namespace: default
  labels:
    app: chhoto
spec:
  selector:
    app: chhoto
  ports:
    - name: panel
      protocol: TCP
      port: 4567
      targetPort: 4567
  type: ClusterIP
