apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mumble-deployment
  namespace: default
  labels:
    app: mumble
spec:
  replicas: 1
  serviceName: mumble-service
  selector:
    matchLabels:
      app: mumble
  template:
    metadata:
      labels:
        app: mumble
    spec:
      # Only x64 image :/
      nodeSelector:
        kubernetes.io/hostname: kevin-laptop
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
      containers:
      - name: mumble
        image: mumblevoip/mumble-server:v1.4.230-6
        volumeMounts:
        - name: mumble-config
          mountPath: /data
        resources:
          requests:
            memory: "64Mi"

      volumes:
      - name: mumble-config
        hostPath:
          path: /mnt/shared_data/k8s/mumble
