---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: grocy
  namespace: default
spec:
  replicas: 1
  serviceName: grocy-service
  selector:
    matchLabels:
      name: grocy
  template:
    metadata:
      labels:
        name: grocy
    spec:
      containers:
      - name: grocy
        image: linuxserver/grocy:v4.0.3-ls221
        ports:
          - containerPort: 80
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 500
          periodSeconds: 60
          timeoutSeconds: 10
          failureThreshold: 5
        volumeMounts:
          - name: db
            mountPath: /config/data/grocy.db
          - name: config
            mountPath: /config/data/config.php
        env:
          - name: PUID
            value: "1000"
          - name: PGID
            value: "1000"
          - name: TZ
            value: "Europe/Berlin"
        resources:
          requests:
            memory: "64Mi"
      volumes:
      - name: db
        hostPath:
          path: /mnt/shared_data/k8s/grocy/grocy.db
      - name: config
        hostPath:
          path: /mnt/shared_data/k8s/grocy/config.php
