apiVersion: apps/v1
kind: Deployment
metadata:
  name: unbound-deployment
  namespace: default
  labels:
    app: unbound
spec:
  replicas: 3
  selector:
    matchLabels:
      app: unbound
  template:
    metadata:
      labels:
        app: unbound
    spec:
      containers:
      - name: unbound
        image: ghcr.io/koskev/unbound:2023.11.25
        resources:
          requests:
            memory: "32Mi"
        volumeMounts:
          - mountPath: /etc/unbound/unbound.conf
            name: unbound-config
            subPath: unbound.conf
      volumes:
        - name: unbound-config
          configMap:
            name: unbound-config
---
apiVersion: v1
kind: Service
metadata:
  name: unbound-service
  namespace: default
  labels:
    app: unbound
spec:
  selector:
    app: unbound
  ports:
    - name: unbound-dns
      protocol: UDP
      port: 53
  type: LoadBalancer
  loadBalancerIP: 192.168.10.6

