---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  chart:
    spec:
      chart: cert-manager
      version: v1.13.3
      sourceRef:
        kind: HelmRepository
        name: cert-manager
        namespace: cert-manager
  interval: 1m0s
  values:
    installCRDs: true
    namespace: "cert-manager"
