---
apiVersion: v1
kind: Service
metadata:
  name: victoria-metrics
  namespace: monitoring
  labels:
    app: victoria-metrics
spec:
  selector:
    app: victoria-metrics
  ports:
    - name: metrics
      protocol: TCP
      port: 8428
      targetPort: 8428
  type: ClusterIP

