#!/bin/sh -e
PREREQS=""
case $1 in
        prereqs) echo "${PREREQS}"; exit 0;;
esac

. /usr/share/initramfs-tools/hook-functions

copy_exec /sbin/resize2fs /sbin
copy_exec /sbin/fdisk /sbin
copy_exec /sbin/cryptsetup /sbin
copy_exec /root/getKey.sh /root/getKey.sh
copy_exec /usr/bin/curl /sbin
copy_exec /usr/bin/jq /sbin
copy_exec /sbin/ntpd /sbin
copy_file /etc/resolv.conf /etc/resolv.conf
copy_file /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt
copy_file /etc/ntpsec/ntp.conf /etc/ntpsec/ntp.conf
