apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
spec:
  project: default
  source:
    chart: ingress-nginx
    repoURL: https://kubernetes.github.io/ingress-nginx
    targetRevision: 4.12.0
    helm:
      releaseName: ingress-nginx
      valuesObject:
        controller:
          allowSnippetAnnotations: true
          service:
            loadBalancerIP: 192.168.10.30
          config:
            proxy-body-size: "50m"
            compute-full-forwarded-for: "true"
            use-forwarded-headers: "true"
            strict-validate-path-type: "false"
          ingressClassResource:
            name: nginx
            controllerValue: "k8s.io/ingress-nginx"

  destination:
    server: "https://kubernetes.default.svc"
    namespace: ingress-nginx
