kind: Secret
apiVersion: v1
metadata:
    name: wg-config
    namespace: default
stringData:
    wg0.conf: ENC[AES256_GCM,data:mHsnB3p5Xpz+M0WtunOp8JY21Zccz90XSCnT1UbRN5XhAKUJ7oT0REcH+EAe0qzU6FXDisktk3+o8XD7baF7CyCFeMPqiAkkBbGdDWbRj2uEOl/vwh2/ohGr9e1Wwkgcz9fWAd4QpWk4nUdXmU3NcA2X9B0IoxZV//YLLhBqnlLA7hbdZUnz1WfNTsG8hKvAOLHYsh2mYUVgqC7iIcS6rgT0mZ1FkSqN7g1gMfs9awLisxB3M5qqWM8Z1AtACZO/cHOq6jpMbhZxpeNWsi80RZz7J2ZMo09NNvom6GrU1RSuwxkOZF1Pv565QQsNXK+xcdtJChg7hYf+rb33KGje4uqa3oaJAyhuv+Bsscr+zSishEewxqJTx9Q4Y0m5kkw63mE1hvqOY+lmc2x3jvAjgHEP2B3lexmssW7P40XpkC98+FDlN4SZCn6rBTzJH7KuF8tyIUMU8GfX6HR9DDTohfftUEc6Z84RnyYnG2j7filmYRcx3JU6gY+EePct/8XubSgo2gqgWA+J/C2AlncUEsztsjV2gjbNbkd8/EssRDYew5DiQqKcwnf+YlsaT07aUsVV1epBlQ==,iv:wFSA/qy8poa4d2STJMZzprhyGOdtiUo2b8IZ2aVlpUg=,tag:Z03HQRucFpW5tVIPFUxnJg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-11-10T19:01:08Z"
    mac: ENC[AES256_GCM,data:/1E+A4VqkFbv1qwwTzXcacRVWFdtRw2XjEJONVBRxvn9tgSTi1ronNvcYnjip9i6QV/eR28xj22jyI2SXiEEwDeyIxbnB96g/CZcIwXDsB7S5srNIaPOVOrNXpZjd0oWF/b7ayKVBt6Qe0fiVExGjH9yZnXGFC1qCOX+40+z8Vk=,iv:FjW4aQxhCGl+422jX0r4kaG1S4lHIdAO2XMTEYaeiyU=,tag:feZV+UOf2qFPui0PoWLe4g==,type:str]
    pgp:
        - created_at: "2023-11-10T19:01:08Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            wV4DJK+IA+cNHtcSAQdAu59QsBqrI0O/a6xS9S4cqJOoLSGNjd3DjPad4dSuwSgw
            qKdRsWWgiqi4hkvXOLCeLHSxKpXHCLWWhsxfuXWor/vj2UP5YbsHG/9NBi0z2oYZ
            0lEBnfZfkHd71eHYUonGScnbDwMWpLbRwgSbhkcsk8RA/qxaFRYJ79qcg+FHVQ6/
            F8loI9hnInfHjQl0Inn/aWOBsx7f1vZctKld4XJin97NIVQ=
            =WDOl
            -----END PGP MESSAGE-----
          fp: 7ED71373082E0FE0F90239710233D0893BBB9872
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
---
kind: Service
apiVersion: v1
metadata:
    name: wireguard-service
    labels:
        app: wireguard
spec:
    selector:
        app: wireguard
    ports:
        - name: wg
          protocol: UDP
          port: 51820
          targetPort: 51820
    type: LoadBalancer
    loadBalancerIP: 192.168.10.10
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-11-10T19:01:08Z"
    mac: ENC[AES256_GCM,data:/1E+A4VqkFbv1qwwTzXcacRVWFdtRw2XjEJONVBRxvn9tgSTi1ronNvcYnjip9i6QV/eR28xj22jyI2SXiEEwDeyIxbnB96g/CZcIwXDsB7S5srNIaPOVOrNXpZjd0oWF/b7ayKVBt6Qe0fiVExGjH9yZnXGFC1qCOX+40+z8Vk=,iv:FjW4aQxhCGl+422jX0r4kaG1S4lHIdAO2XMTEYaeiyU=,tag:feZV+UOf2qFPui0PoWLe4g==,type:str]
    pgp:
        - created_at: "2023-11-10T19:01:08Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            wV4DJK+IA+cNHtcSAQdAu59QsBqrI0O/a6xS9S4cqJOoLSGNjd3DjPad4dSuwSgw
            qKdRsWWgiqi4hkvXOLCeLHSxKpXHCLWWhsxfuXWor/vj2UP5YbsHG/9NBi0z2oYZ
            0lEBnfZfkHd71eHYUonGScnbDwMWpLbRwgSbhkcsk8RA/qxaFRYJ79qcg+FHVQ6/
            F8loI9hnInfHjQl0Inn/aWOBsx7f1vZctKld4XJin97NIVQ=
            =WDOl
            -----END PGP MESSAGE-----
          fp: 7ED71373082E0FE0F90239710233D0893BBB9872
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: wireguard
spec:
    replicas: 1
    selector:
        matchLabels:
            app: wireguard
    template:
        metadata:
            labels:
                app: wireguard
        spec:
            containers:
                - name: wireguard
                  image: lscr.io/linuxserver/wireguard:v1.0.20210914-ls11
                  env:
                    - name: PUID
                      value: "1000"
                    - name: GUID
                      value: "1000"
                    - name: TZ
                      value: Europe/Berlin
                  securityContext:
                    capabilities:
                        add:
                            - NET_ADMIN
                    privileged: true
                  resources:
                    requests:
                        memory: 64Mi
                        cpu: 100m
                    limits:
                        memory: 256Mi
                  volumeMounts:
                    - name: wg-config
                      mountPath: /config/wg_confs
            volumes:
                - name: wg-config
                  secret:
                    secretName: wg-config
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-11-10T19:01:08Z"
    mac: ENC[AES256_GCM,data:/1E+A4VqkFbv1qwwTzXcacRVWFdtRw2XjEJONVBRxvn9tgSTi1ronNvcYnjip9i6QV/eR28xj22jyI2SXiEEwDeyIxbnB96g/CZcIwXDsB7S5srNIaPOVOrNXpZjd0oWF/b7ayKVBt6Qe0fiVExGjH9yZnXGFC1qCOX+40+z8Vk=,iv:FjW4aQxhCGl+422jX0r4kaG1S4lHIdAO2XMTEYaeiyU=,tag:feZV+UOf2qFPui0PoWLe4g==,type:str]
    pgp:
        - created_at: "2023-11-10T19:01:08Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            wV4DJK+IA+cNHtcSAQdAu59QsBqrI0O/a6xS9S4cqJOoLSGNjd3DjPad4dSuwSgw
            qKdRsWWgiqi4hkvXOLCeLHSxKpXHCLWWhsxfuXWor/vj2UP5YbsHG/9NBi0z2oYZ
            0lEBnfZfkHd71eHYUonGScnbDwMWpLbRwgSbhkcsk8RA/qxaFRYJ79qcg+FHVQ6/
            F8loI9hnInfHjQl0Inn/aWOBsx7f1vZctKld4XJin97NIVQ=
            =WDOl
            -----END PGP MESSAGE-----
          fp: 7ED71373082E0FE0F90239710233D0893BBB9872
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
---
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-11-10T19:01:08Z"
    mac: ENC[AES256_GCM,data:/1E+A4VqkFbv1qwwTzXcacRVWFdtRw2XjEJONVBRxvn9tgSTi1ronNvcYnjip9i6QV/eR28xj22jyI2SXiEEwDeyIxbnB96g/CZcIwXDsB7S5srNIaPOVOrNXpZjd0oWF/b7ayKVBt6Qe0fiVExGjH9yZnXGFC1qCOX+40+z8Vk=,iv:FjW4aQxhCGl+422jX0r4kaG1S4lHIdAO2XMTEYaeiyU=,tag:feZV+UOf2qFPui0PoWLe4g==,type:str]
    pgp:
        - created_at: "2023-11-10T19:01:08Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            wV4DJK+IA+cNHtcSAQdAu59QsBqrI0O/a6xS9S4cqJOoLSGNjd3DjPad4dSuwSgw
            qKdRsWWgiqi4hkvXOLCeLHSxKpXHCLWWhsxfuXWor/vj2UP5YbsHG/9NBi0z2oYZ
            0lEBnfZfkHd71eHYUonGScnbDwMWpLbRwgSbhkcsk8RA/qxaFRYJ79qcg+FHVQ6/
            F8loI9hnInfHjQl0Inn/aWOBsx7f1vZctKld4XJin97NIVQ=
            =WDOl
            -----END PGP MESSAGE-----
          fp: 7ED71373082E0FE0F90239710233D0893BBB9872
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
