---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: brouter
  namespace: default
spec:
  chart:
    spec:
      chart: brouter
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: brouter
  interval: 1m0s
  values:
    ingress:
      enabled: true
      ingress_class: nginx-external
      host: brouter.kokev.de
      tls:
        enabled: true
        issuer: "kokev-issuer"
        secret: brouter-tls
    brouter:
      image:
        repository: ghcr.io/koskev/brouter
        pullPolicy: IfNotPresent
        tag: "2024.03.06"
      volumes:
        - name: segments
          hostPath:
            path: /mnt/shared_data/k8s/brouter/segments4
    brouter_web:
      image:
        repository: ghcr.io/koskev/brouter-web
        pullPolicy: IfNotPresent
        tag: "2024.03.06"
