apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: jellyfin-ingress
    namespace: default
spec:
    ingressClassName: nginx
    rules:
        - host: jellyfin.kokev.de
          http:
            paths:
                - pathType: Prefix
                  backend:
                    service:
                        name: jellyfin-service
                        port:
                            number: 80
                  path: /
    tls:
        - hosts:
            - jellyfin.kokev.de
          secretName: kokev-wildcard-tls
