{ applications+: { monitoring+: { config+: (import 'argocd/applications/monitoring/config.libsonnet'),
},
 postgres+: { cnpg+: { config+: (import 'argocd/applications/postgres/cnpg/config.libsonnet'),
},
},
 cert_manager+: { config+: (import 'argocd/applications/cert-manager/config.libsonnet'),
 desec+: { config+: (import 'argocd/applications/cert-manager/desec/config.libsonnet'),
},
},
 openbao+: { config+: (import 'argocd/applications/openbao/config.libsonnet'),
},
 authelia+: { config+: (import 'argocd/applications/authelia/config.libsonnet'),
},
 renovate+: { config+: (import 'argocd/applications/renovate/config.libsonnet'),
},
 config+: (import 'argocd/applications/config.libsonnet'),
},
 argocd+: { config+: (import 'argocd/argocd/config.libsonnet'),
},
 globals+: { config+: (import 'argocd/globals/config.libsonnet'),
},
}
