{ applications+: { postgres+: { cnpg+: { config+: (import 'argocd/applications/postgres/cnpg/config.libsonnet'),
},
},
 cert_manager+: { config+: (import 'argocd/applications/cert-manager/config.libsonnet'),
},
 openbao+: { config+: (import 'argocd/applications/openbao/config.libsonnet'),
},
 config+: (import 'argocd/applications/config.libsonnet'),
},
 argocd+: { config+: (import 'argocd/argocd/config.libsonnet'),
},
 globals+: { config+: (import 'argocd/globals/config.libsonnet'),
},
}
