apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
    name: private-issuer
    namespace: cert-manager
spec:
    acme:
        # The ACME server URL
        server: https://acme-v02.api.letsencrypt.org/directory
        # Email address used for ACME registration
        email: ENC[AES256_GCM,data:h+g8wpleqmoBi/tsKfXjaOuCJN6L,iv:yuI8C5TDfXbGwJO1uT5E0IY64IrrScHxH4iEQobEoUc=,tag:xkx/fEXqFoLGr+OUMYdRmw==,type:str]
        # Name of a secret used to store the ACME account private key
        privateKeySecretRef:
            name: private-issuer
        # Enable the HTTP-01 challenge provider
        solvers:
            - http01:
                ingress:
                    ingressClassName: traefik-external
sops:
    lastmodified: "2025-09-06T13:50:38Z"
    mac: ENC[AES256_GCM,data:Vf+znUaxN/vETKKyNxjbdifJ6D/7t4GfIbKIDtiXfyyIzL+D7ZqovbTq45pLUC/VvF4an012Mn4iCqjsUWsfrCAgm62e1yLeisV63tXUdfmml3mO43VMvE7iBy56w3uGmF6bpydmKAdQ6hV32zbEPUqmbTJsohULoeKa0zoS76g=,iv:fuqdiru3BieiXLU7YBwimIl+5pgwFnahikUcnzugbPs=,tag:IE+CgriwOsXDxRv5BJqufw==,type:str]
    pgp:
        - created_at: "2024-02-18T11:25:54Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            wV4DJK+IA+cNHtcSAQdAxB9LK3hNMvs+PAjeh61PAn14xuvMtXEGWg9VIkH2IR0w
            dE248qnN9Q/9RFqKU/d6JGY1QhTHmHGJYtY39eDJtsJKgs/OT7SvQabr0lbbg7jU
            0lEB4+yQV8M7mNyjlmkYqfvxHl1KV7Ea7xkv9EOCyVq9ktCAIDiIcKk/COL/C7DG
            TBlHlVJbZmgTeFkQjPuRqtRB9A/PaQCIJKcXBvCOt6dI7XI=
            =z9pU
            -----END PGP MESSAGE-----
          fp: 7ED71373082E0FE0F90239710233D0893BBB9872
    encrypted_regex: ^(data|stringData|email|host|hosts)$
    version: 3.10.2
