apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
    name: private-issuer
    namespace: cert-manager
spec:
    acme:
        # The ACME server URL
        server: https://acme-v02.api.letsencrypt.org/directory
        # Email address used for ACME registration
        email: ENC[AES256_GCM,data:h+g8wpleqmoBi/tsKfXjaOuCJN6L,iv:yuI8C5TDfXbGwJO1uT5E0IY64IrrScHxH4iEQobEoUc=,tag:xkx/fEXqFoLGr+OUMYdRmw==,type:str]
        # Name of a secret used to store the ACME account private key
        privateKeySecretRef:
            name: private-issuer
        # Enable the HTTP-01 challenge provider
        solvers:
            - http01:
                ingress:
                    ingressClassName: nginx-external
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-02-18T11:25:54Z"
    mac: ENC[AES256_GCM,data:6Ht7MtUrfIaE2QOzhkjnMp/IPZOOCOcy0s3S8RpYYBVZz6k6/rIrfW4SBtbRaPufMsxWcx1AI2UMyzY/yV4e5m9wVvz4pFJDH891++O6Fo0unGb7G8aRFoHGawN2dB/rvJRIOCZxp3MP4eCCSeMtHXJSLp1aJYy3TooxhcxD7p0=,iv:XnkALVIX5JM+jFSIp+rXcsqlAvi/5wlp6iZ1VHojPT0=,tag:1XaPUX76lHujYO924Zzvjw==,type:str]
    pgp:
        - created_at: "2024-02-18T11:25:54Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            wV4DJK+IA+cNHtcSAQdAxB9LK3hNMvs+PAjeh61PAn14xuvMtXEGWg9VIkH2IR0w
            dE248qnN9Q/9RFqKU/d6JGY1QhTHmHGJYtY39eDJtsJKgs/OT7SvQabr0lbbg7jU
            0lEB4+yQV8M7mNyjlmkYqfvxHl1KV7Ea7xkv9EOCyVq9ktCAIDiIcKk/COL/C7DG
            TBlHlVJbZmgTeFkQjPuRqtRB9A/PaQCIJKcXBvCOt6dI7XI=
            =z9pU
            -----END PGP MESSAGE-----
          fp: 7ED71373082E0FE0F90239710233D0893BBB9872
    encrypted_regex: ^(data|stringData|email|host|hosts)$
    version: 3.8.1
