apiVersion: db.movetokube.com/v1alpha1
kind: PostgresUser
metadata:
  name: hass
  namespace: default
spec:
  role: hass
  database: hass-db
  secretName: hass-db-secret
  privileges: OWNER     # Can be OWNER/READ/WRITE
  secretTemplate:       # Output secrets can be customized using standard Go templates
    database.yaml: |
      db_url: postgresql://{{.Role}}:{{.Password}}@{{.Host}}/{{.Database}}?sslmode=disable
