apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: hass-deployment
  namespace: default
  labels:
    app: hass
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hass
  template:
    metadata:
      labels:
        app: hass
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
      containers:
      - name: hass
        image: ghcr.io/home-assistant/home-assistant:2023.11.2
        ports:
        - containerPort: 8123
          protocol: TCP
        volumeMounts:
        - name: hass-config
          mountPath: /config
        livenessProbe:
          httpGet:
            path: /
            port: 8123
          initialDelaySeconds: 500
          periodSeconds: 60
          timeoutSeconds: 10
          failureThreshold: 5

      nodeSelector:
        disk: ssd
      volumes:
      - name: hass-config
        hostPath:
          path: /mnt/shared_data/k8s/hass/config

---
apiVersion: v1
kind: Service
metadata:
  name: hass-service
  namespace: default
  labels:
    app: hass
spec:
  selector:
    app: hass
  ports:
    - name: panel
      protocol: TCP
      port: 80
      targetPort: 8123
  type: ClusterIP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hass-ingress
  namespace: default
  annotations:
    cert-manager.io/cluster-issuer: "kokev-issuer"
spec:
  ingressClassName: nginx
  rules:
    - host: hass.kokev.de
      http:
        paths:
          - pathType: Prefix
            backend:
              service:
                name: hass-service
                port:
                  number: 80
            path: /
  # This section is only required if TLS is to be enabled for the Ingress
  tls:
    - hosts:
      - hass.kokev.de
      secretName: hass-tls
