---
kind: Service
apiVersion: v1
metadata:
    name: wireguard-service
    namespace: default
    labels:
        app: wireguard
spec:
    selector:
        app: wireguard
    ports:
        - name: wg
          protocol: UDP
          port: 51820
          targetPort: 51820
    type: LoadBalancer
    loadBalancerIP: 192.168.10.10
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: wireguard
    namespace: default
spec:
    replicas: 1
    selector:
        matchLabels:
            app: wireguard
    template:
        metadata:
            labels:
                app: wireguard
        spec:
            containers:
                - name: wireguard
                  image: lscr.io/linuxserver/wireguard:1.0.20210914-r4-ls68
                  env:
                      - name: PUID
                        value: "1000"
                      - name: GUID
                        value: "1000"
                      - name: TZ
                        value: Europe/Berlin
                  securityContext:
                      capabilities:
                          add:
                              - NET_ADMIN
                      privileged: true
                  resources:
                      requests:
                          memory: 64Mi
                          cpu: 100m
                      limits:
                          memory: 256Mi
                  volumeMounts:
                      - name: wg-config
                        mountPath: /config/wg_confs
            volumes:
                - name: wg-config
                  secret:
                      secretName: wg-config
