---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
  namespace: metallb-system
spec:
  chart:
    spec:
      chart: metallb
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: metallb
  interval: 1m0s
  values:
    controller:
      priorityClassName: "system-cluster-critical"
      resources:
        limits:
          cpu: 100m
          memory: 100Mi
    speaker:
      priorityClassName: "system-cluster-critical"
      resources:
        limits:
          cpu: 100m
          memory: 200Mi
