apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  source:
    path: argocd/applications
    repoURL: https://github.com/koskev/k8s
    targetRevision: HEAD
    directory:
      recurse: true
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
