apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: default
  source:
    chart: argo-cd
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: 7.7.16
    helm:
      releaseName: argocd
      valuesObject:
        global:
          domain: argocd.kokev.de
        redis:
          image:
            repository: valkey/valkey
            tag: 8.0.2
        configs:
          params:
            server.insecure: true
        server:
          ingress:
            enabled: true
            ingressClassName: nginx
            annotations:
              cert-manager.io/cluster-issuer: "kokev-issuer"
            extraTls:
              - hosts:
                  - argocd.kokev.de
                secretName: argocd-tls

  destination:
    server: "https://kubernetes.default.svc"
    namespace: argocd
