apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  source:
    directory:
      jsonnet:
        libs:
          - lib
    path: argocd
    repoURL: https://github.com/koskev/k8s
    targetRevision: HEAD
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
