apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-pv
  namespace: monitoring
  labels:
    storage: grafana
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  hostPath:
    path: /mnt/shared_data/k8s/prometheus/grafana_data
    type: DirectoryOrCreate
  storageClassName: 'local'
