apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-db
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  hostPath:
    path: /mnt/shared_data/k8s/prometheus/prometheus_data
    type: DirectoryOrCreate
  storageClassName: 'local'
