---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: prometheus
  namespace: default
spec:
  chart:
    spec:
      chart: kube-prometheus-stack
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: prometheus
  interval: 1m0s
  values:
    grafana:
      ingress:
        enabled: true
        ingressClassName: nginx
        paths:
          - /
        hosts:
          - grafana.kokev.de
        tls:
          - hosts:
            - grafana.kokev.de
            secretName: kokev-wildcard-tls
