---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: prometheus
  namespace: monitoring
spec:
  chart:
    spec:
      chart: kube-prometheus-stack
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: prometheus
  interval: 1m0s
  values:
    namespaceOverride: monitoring
    grafana:
      ingress:
        enabled: true
        ingressClassName: nginx
        annotations:
          cert-manager.io/cluster-issuer: "kokev-issuer"
        paths:
          - /
        hosts:
          - grafana.kokev.de
        tls:
          - hosts:
            - grafana.kokev.de
            secretName: grafana-tls
    prometheus:
      prometheusSpec:
        additionalScrapeConfigs:
          - job_name: OpenWrt
            static_configs:
              - targets: ['openwrt.lan:9100']
