apiVersion: v1
kind: Service
metadata:
  name: whatsapp-bridge-service
  namespace: default
  labels:
    app: whatsapp-bridge
spec:
  selector:
    app: whatsapp-bridge
  ports:
    - name: bridge
      protocol: TCP
      port: 29318
      targetPort: 29318
    - name: metrics
      protocol: TCP
      port: 9100
      targetPort: 9100
  type: ClusterIP
