apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: whatsapp-bridge-deployment
  namespace: default
  labels:
    app: whatsapp-bridge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: whatsapp-bridge
  template:
    metadata:
      labels:
        app: whatsapp-bridge
    spec:
      containers:
      - name: whatsapp-bridge
        image: dock.mau.dev/mautrix/whatsapp:v0.10.7
        command: ["su-exec"]
        args: ["$UID:$GID", "/usr/bin/mautrix-whatsapp", "--no-update", "-c", "/data/config.yaml"]
        ports:
        - containerPort: 29318
          protocol: TCP
        volumeMounts:
        - name: whatsapp-bridge-config
          mountPath: /data
        resources:
          requests:
            memory: "64Mi"
      nodeSelector:
        disk: ssd
      volumes:
      - name: whatsapp-bridge-config
        secret:
          secretName: whatsapp-bridge-config
---

