---
apiVersion: v1
kind: Service
metadata:
  name: influxdb
  namespace: monitoring
  labels:
    app: influxdb
spec:
  selector:
    app: influxdb
  ports:
    - name: influx
      protocol: TCP
      port: 8086
      targetPort: 8086
  type: ClusterIP

