---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: hms-mqtt
  namespace: default
spec:
  valuesFrom:
    - kind: Secret
      name: hms-secrets
      valuesKey: mqtt_password
      targetPath: hms_mqtt.mqtt.password
    - kind: Secret
      name: hms-secrets
      valuesKey: mqtt_password
      targetPath: hms_mqtt.simple_mqtt.password
    - kind: Secret
      name: hms-secrets
      valuesKey: alias_serial
      targetPath: hms_mqtt.mqtt.serial_aliases[0].serial
    - kind: Secret
      name: hms-secrets
      valuesKey: alias_name
      targetPath: hms_mqtt.mqtt.serial_aliases[0].alias

  chart:
    spec:
      chart: hms-mqtt-chart
      reconcileStrategy: ChartVersion
      version: 0.1.3
      sourceRef:
        kind: HelmRepository
        name: hms-mqtt-chart
  interval: 1m0s
  values:
    hms_mqtt:
      inverter_hosts:
        - solar.lan
      simple_mqtt:
        host: emqx
        port: 1883
        username: hms

      mqtt:
        host: emqx
        port: 1883
        username: hms
        base_topic: "solar"
    image:
      repository: ghcr.io/koskev/hms-mqtt-publisher
      pullPolicy: Always
      tag: "2024.04.19"

