apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cilium
  namespace: cilium
spec:
  project: default
  source:
    chart: cilium
    repoURL: https://helm.cilium.io/
    targetRevision: v1.17.0
    helm:
      releaseName: cilium
      valuesObject:
        defaultLBServiceIPAM: none
        l2announcements:
          enabled: true
        encryption:
          enabled: true
          type: wireguard

  destination:
    server: "https://kubernetes.default.svc"
    namespace: kube-system
