apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: brouter
spec:
  project: default
  source:
    chart: brouter
    repoURL: https://koskev.github.io/brouter-chart
    helm:
      releaseName: brouter
      valuesObject:
        ingress:
          enabled: true
          ingress_class: nginx-external
          host: brouter.kokev.de
          tls:
            enabled: true
            issuer: "kokev-issuer"
            secret: brouter-tls
        brouter:
          enabled: true
          volumes:
            - name: segments
              hostPath:
                path: /mnt/shared_data/k8s/brouter/segments4
        brouter_react:
          enabled: true
          image:
            repository: ghcr.io/koskev/brouter-react
            pullPolicy: Always

  destination:
    server: "https://kubernetes.default.svc"
    namespace: default
