local argocd = import 'argocd.libsonnet';
{
  apps: [
    argocd.appSettings(name='default', recursive=false, passInput=false),
    argocd.appSettings(name='cert-manager'),
    argocd.appSettings(name='external-secrets'),
    argocd.appSettings(name='ingress-traefik', passInput=false),
    argocd.appSettings(name='kube-flannel', passInput=false),
    argocd.appSettings(name='matrix', passInput=false),
    argocd.appSettings(name='metallb-system', passInput=false),
    argocd.appSettings(name='monitoring'),
    argocd.appSettings(name='openbao'),
    argocd.appSettings(name='postgres'),
    argocd.appSettings(name='emqx'),
    argocd.appSettings(name='reloader'),
    argocd.appSettings(name='navidrome'),
    // argocd.appSettings(name='trivy'),
    argocd.appSettings(name='paperless'),
    argocd.appSettings(name='forgejo', passInput=false),
    argocd.appSettings(name='automation', passInput=false),
    argocd.appSettings(name='grafana', exclude='dashboards/*'),
    argocd.appSettings(name='kube-system'),
    argocd.appSettings(name='fittrackee', passInput=false),
    argocd.appSettings(name='immich', passInput=false),
    argocd.appSettings(name='borg'),
    argocd.appSettings(name='authelia'),
  ],
}
