local argocd = import 'argocd.libsonnet';
{
  apps: [
    argocd.appSettings(name='default', recursive=false),
    argocd.appSettings(name='cert-manager', passInput=true),
    argocd.appSettings(name='external-secrets', passInput=true),
    //argocd.appSettings(name='ingress-nginx'),
    argocd.appSettings(name='ingress-traefik'),
    argocd.appSettings(name='kube-flannel'),
    argocd.appSettings(name='matrix'),
    argocd.appSettings(name='metallb-system'),
    argocd.appSettings(name='monitoring', passInput=true),
    argocd.appSettings(name='openbao', passInput=true),
    argocd.appSettings(name='postgres', passInput=true),
    argocd.appSettings(name='emqx', passInput=true),
    argocd.appSettings(name='reloader'),
    argocd.appSettings(name='navidrome', passInput=true),
    // argocd.appSettings(name='trivy'),
    argocd.appSettings(name='paperless'),
    argocd.appSettings(name='forgejo'),
    argocd.appSettings(name='automation'),
    argocd.appSettings(name='grafana', exclude='dashboards/*'),
    argocd.appSettings(name='kube-system'),
    argocd.appSettings(name='fittrackee'),
    argocd.appSettings(name='immich'),
    argocd.appSettings(name='borg'),
    argocd.appSettings(name='authelia', passInput=true),
  ],
}
