apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openbao
  namespace: argocd
spec:
  project: default
  source:
    chart: openbao
    repoURL: https://openbao.github.io/openbao-helm
    targetRevision: 0.8.1
    helm:
      releaseName: openbao
      valuesObject:
        server:
          ingress:
            enabled: true
            annotations:
              cert-manager.io/cluster-issuer: "kokev-issuer"
            ingressClassName: nginx
            hosts:
              - host: vault.kokev.de
            tls:
              - secretName: vault-tls
                hosts:
                  - vault.kokev.de
          ha:
            enabled: true
            config: |
              ui = true

              listener "tcp" {
                tls_disable = 1
                address = "[::]:8200"
                cluster_address = "[::]:8201"
              }
              storage "postgresql" {
                ha_enabled = "true"
              }

              service_registration "kubernetes" {}
          extraSecretEnvironmentVars:
            - envName: BAO_PG_CONNECTION_URL
              secretKey: POSTGRES_URL_NO_SSL
              secretName: openbao-openbao

  destination:
    server: "https://kubernetes.default.svc"
    namespace: openbao
