apiVersion: v1
kind: Secret
metadata:
  name: test-secret
  namespace: default
  annotations:
    vault.security.banzaicloud.io/vault-addr: "http://openbao.openbao:8200" # optional, the address of the Vault service, default values is https://vault:8200
    vault.security.banzaicloud.io/vault-role: "openbao-webhook-vault-secrets-webhook" # optional, the default value is the name of the ServiceAccount the Pod runs in, in case of Secrets and ConfigMaps it is "default"
    vault.security.banzaicloud.io/vault-skip-verify: "false" # optional, skip TLS verification of the Vault server certificate
    vault.security.banzaicloud.io/vault-agent: "false" # optional, if true, a Vault Agent will be started to do Vault authentication, by default not needed and vault-env will do Kubernetes Service Account based Vault authentication
    vault.security.banzaicloud.io/vault-path: "kubernetes" # optional, the Kubernetes Auth mount path in Vault the default value is "kubernetes"
stringData:
  test: vault:secrets/data/chhoto/#password
