apiVersion: v1
kind: Secret
metadata:
    name: gitlab-secret
    namespace: gitlab
type: Opaque
stringData:
    url: ENC[AES256_GCM,data:x2N+QLPhj95+sBkaCDYlpOUZ,iv:pVzvbT+jp9e4OJ0chY/ifgZyomhyfEsi4mwuLsj5/ko=,tag:LamA7U7H+/FGEY+MbGx3Tw==,type:str]
    token: ENC[AES256_GCM,data:Znl0GjtI0VR0KcG6cwIr+6YvaUzPwUQNWA==,iv:LPt8f7RShaomgUN7jEr1f2en7cc1TWFQ4p9oAQUo6/Y=,tag:bg4TWGVoGK+PbJ2kONXGyw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-06-26T15:14:38Z"
    mac: ENC[AES256_GCM,data:mVA7I1xi1+RTctqNnbhR/LaJVpClVEXN/4jDglldfqkJ6kE+29GFaXY7bOuBJhU+d9p9xLBAWwsMQdU1YakKqEQ8sLDRKdCAl0j1EzqwgTAV9YeUB0UurpajvXdHdzqMuNk7u0LAorcRPvFVYWgeA+w7vwdp0e32NXhZZSDjXvY=,iv:Q1ButDnMCydc2H0McIZhV6sDFF+MRaewVKJ8VO6ea7g=,tag:PG2j7wfk+tVANqpRXa01Pg==,type:str]
    pgp:
        - created_at: "2024-06-26T15:14:38Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            wV4DJK+IA+cNHtcSAQdAfw/wYKKufOmv1PuJ6fpp9bTLg3sJy/gyFkRSEHCZHRYw
            YcmRfINKiuZ2KeK7tzgfTEsormpvtFOwFzCXYtYGi0Y2aCPrxP8sVYxB3NBefXpt
            0lEBvrixgAjJ0XpPgJUbbcs+aacgHeSprjkkt1JVlm06JcgAE0c5haSNDZiE8nAU
            N4ETmxLfpzrXvAKVeuT3HnaP4wrYuPfT76LVICp6LPOfrwE=
            =UXjl
            -----END PGP MESSAGE-----
          fp: 7ED71373082E0FE0F90239710233D0893BBB9872
    encrypted_regex: ^(data|stringData|email|host|hosts)$
    version: 3.8.1
