---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gitlab
  namespace: gitlab
spec:
  valuesFrom:
    - kind: Secret
      name: gitlab-secret
      valuesKey: url
      targetPath: gitlabUrl
    - kind: Secret
      name: gitlab-secret
      valuesKey: token
      targetPath: runnerRegistrationToken
  chart:
    spec:
      chart: gitlab-runner
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: gitlab
  interval: 1m0s
  values:
    rbac:
      create: true
    runners:
      config: |
        [[runners]]
          concurrent = 1
          [runners.kubernetes]
            node_selector_overwrite_allowed = ".*"
            helper_image = "ghcr.io/loft-orbital/gitlab-runner-helper:alpine-latest-v17.1.0"

