---
apiVersion: v1
kind: Service
metadata:
  name: mqtt-exporter
  namespace: monitoring
  labels:
    app: mqtt-exporter
spec:
  selector:
    app: mqtt-exporter
  ports:
    - name: panel
      protocol: TCP
      port: 9000
      targetPort: 9000
  type: ClusterIP
