apiVersion: apps/v1
kind: Deployment
metadata:
  name: mqtt-exporter-deployment
  namespace: monitoring
  labels:
    app: mqtt-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mqtt-exporter
  template:
    metadata:
      labels:
        app: mqtt-exporter
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
      containers:
      - name: mqtt-exporter
        image: kpetrem/mqtt-exporter
        ports:
        - containerPort: 9000
          protocol: TCP
        env:
          - name: MQTT_ADDRESS
            value: "emqx.default"
          - name: MQTT_USER
            value: mqtt-exporter
          - name: MQTT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mqtt-exporter-secret
                key: mqtt_password
        livenessProbe:
          httpGet:
            path: /
            port: 9000
          initialDelaySeconds: 500
          periodSeconds: 60
          timeoutSeconds: 10
          failureThreshold: 5
        resources:
          requests:
            memory: "64Mi"
