apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: signal-bridge-deployment
  namespace: default
  labels:
    app: signal-bridge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: signal-bridge
  template:
    metadata:
      labels:
        app: signal-bridge
    spec:
      containers:
      - name: signal-bridge
        image: dock.mau.dev/mautrix/signal:v0.5.0
        command: ["su-exec"]
        args: ["$UID:$GID", "/usr/bin/mautrix-signal", "--no-update", "-c", "/data/config.yaml"]
        ports:
        - containerPort: 29328
          protocol: TCP
        volumeMounts:
        - name: signal-bridge-config
          mountPath: /data
        resources:
          requests:
            memory: "128Mi"
      volumes:
      - name: signal-bridge-config
        secret:
          secretName: signal-bridge-config
---

