---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: sanejs-data
spec:
  storageClassName: kadalu.arbiter-pool
  accessModes:
    - ReadWriteOnce # You can also provide 'ReadWriteMany' here
  resources:
    requests:
      storage: 500Mi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: sanejs-config
spec:
  storageClassName: kadalu.arbiter-pool
  accessModes:
    - ReadWriteOnce # You can also provide 'ReadWriteMany' here
  resources:
    requests:
      storage: 50Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sanejs-deployment
  namespace: default
  labels:
    app: sanejs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sanejs
  template:
    metadata:
      labels:
        app: sanejs
    spec:
      containers:
      - name: sanejs
        image: sbs20/scanservjs:v3.0.3
        ports:
        - containerPort: 8080
          protocol: TCP
        volumeMounts:
        - name: scanned-files
          mountPath: /var/lib/scanservjs/output
        - name: config
          mountPath: /app/config
        env:
          - name: SANED_NET_HOSTS
            value: "rpi-cluster-02.lan" # TODO: "saned" does not work. Need to learn why
        resources:
          requests:
            memory: "64Mi"
      volumes:
        # TODO: change to pvc
      - name: scanned-files
        persistentVolumeClaim:
          claimName: sanejs-data
      - name: config
        persistentVolumeClaim:
          claimName: sanejs-config
---
apiVersion: v1
kind: Service
metadata:
  name: sanejs-service
  namespace: default
  labels:
    app: sanejs
spec:
  selector:
    app: sanejs
  ports:
    - name: sanejs-http
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sanejs-ingress
  namespace: default
spec:
  ingressClassName: nginx
  rules:
    - host: scanner.lan
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: sanejs-service
                port:
                  number: 8080
