---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: hostapd
  namespace: default
spec:
  valuesFrom:
    - kind: Secret
      name: hostapd-secret
      valuesKey: ssid
      targetPath: hostapd.ssid
    - kind: Secret
      name: hostapd-secret
      valuesKey: password
      targetPath: hostapd.password
  chart:
    spec:
      chart: hostapd
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: hostapd
  interval: 1m0s
