---
apiVersion: glusterd-operator.storage/v1
kind: GlusterdStorage
metadata:
  name: database-storage
  namespace: storage
spec:
  type: Arbiter
  options:
    - group db-workload
  nodes:
    - name: kevin-laptop
      storagePath: "/mnt/hdd_gluster/database-storage"
    - name: raspberrypi-server
      storagePath: "/mnt/hdd_gluster/database-storage"
    - name: rpi-server2
      storagePath: "/data/glusterfs/database-storage-arbiter"
