---
apiVersion: v1
kind: Service
metadata:
  name: mumble-service
  namespace: default
  labels:
    app: mumble
  annotations:
    external-dns.alpha.kubernetes.io/hostname: "mumble.kokev.de"
spec:
  selector:
    app: mumble
  ports:
    - name: control
      protocol: TCP
      port: 64738
      targetPort: 64738
    - name: voice
      protocol: UDP
      port: 64738
      targetPort: 64738
  type: LoadBalancer
