apiVersion: v1
kind: PersistentVolume
metadata:
  name: vault-pv
  namespace: vault
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  hostPath:
    path: /mnt/shared_data/k8s/vault/data
    type: DirectoryOrCreate
  storageClassName: 'vault-storage'
