apiVersion: db.movetokube.com/v1alpha1
kind: PostgresUser
metadata:
  name: vault-db-user
  namespace: vault
spec:
  role: vault
  database: vault-db       # This references the Postgres CR
  secretName: vault-storage-secret
  privileges: OWNER     # Can be OWNER/READ/WRITE
  secretTemplate:       # Output secrets can be customized using standard Go templates
    config.hcl: |
        storage "postgresql" {
            connection_url = "postgres://{{.Role}}:{{.Password}}@{{.Host}}/{{.Database}}?sslmode=disable"
        }
