---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vault
  namespace: vault
spec:
  chart:
    spec:
      chart: vault
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: vault
  interval: 1m0s
  values:
    server:
      dataStorage:
        enabled: false
      volumes:
        - name: storage-config
          secret:
            defaultMode: 420
            secretName: vault-storage-secret-vault-db-user
      volumeMounts:
        - name: storage-config
          mountPath: '/vault/userconfig/vault-storage-config'
          readOnly: true
      extraArgs: '-config=/vault/userconfig/vault-storage-config/config.hcl'
      ingress:
        enabled: true
        ingressClassName: nginx
        annotations:
          cert-manager.io/cluster-issuer: "kokev-issuer"
        hosts:
          - host: vault.kokev.de
        tls:
          - hosts:
            - vault.kokev.de
            secretName: vault-tls
